# Generated by Django 4.2.6 on 2023-10-16 01:29

import django.db.models.deletion
import jsonfield.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("point", models.IntegerField(default=0)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("str", "String"),
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("bool", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "DateTime"),
                            ("time", "Time"),
                        ],
                        default="str",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True, related_name="entities", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Office",
                "verbose_name_plural": "Offices",
            },
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                ("uuid", models.UUIDField(blank=True, null=True)),
                ("submitted_by", models.CharField(max_length=20)),
                ("submitted_for", models.CharField(max_length=255, null=True)),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("dila", "Dila"),
                            ("muqami", "Muqami"),
                            ("state", "State"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("month", models.IntegerField(null=True)),
                ("year", models.IntegerField(null=True)),
                ("value_str", models.TextField(blank=True, null=True)),
                ("value_int", models.IntegerField(blank=True, null=True)),
                ("value_float", models.FloatField(blank=True, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_date", models.DateTimeField(blank=True, null=True)),
                ("value_datetime", models.DateTimeField(blank=True, null=True)),
                ("value_time", models.TimeField(blank=True, null=True)),
                (
                    "value_json",
                    jsonfield.fields.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="api.attribute",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="api.entity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="api.entity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attribute",
            unique_together={("entity", "slug")},
        ),
    ]
