# Generated by Django 4.2.6 on 2023-11-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="value",
            name="value_file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
