# Generated by Django 2.2.1 on 2021-06-06 14:58

from django.db import migrations, models


def add_user_details(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.filter(mkanid__isnull=False):
        if not user.user_details:
            user.user_details = user.get_user_data()
            user.save(update_fields=["user_details"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_details",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RunPython(add_user_details),
    ]
