# Generated by Django 4.2.6 on 2023-10-16 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_user_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginauditmodel",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_details",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
