# Generated by Django 4.2.6 on 2023-12-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_loginauditmodel_user_alter_user_user_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="post",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
